// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtkZAmmpSc41zwdGDHKjks1Lww1qxQLCw',
    appId: '1:581784052392:web:5cfc720956301dcf7a989d',
    messagingSenderId: '581784052392',
    projectId: 'chorechain-61e97',
    authDomain: 'chorechain-61e97.firebaseapp.com',
    storageBucket: 'chorechain-61e97.firebasestorage.app',
    measurementId: 'G-PJ6J1HXMBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw9iZSNj27OeWnDBwVQ5zbkXTV5R6LlRg',
    appId: '1:581784052392:android:d0ba65aa0bf90df07a989d',
    messagingSenderId: '581784052392',
    projectId: 'chorechain-61e97',
    storageBucket: 'chorechain-61e97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzN7WZwDh5mnVyukbiY6kgwwSfbKhko_8',
    appId: '1:581784052392:ios:9a0dd7cb8bab78007a989d',
    messagingSenderId: '581784052392',
    projectId: 'chorechain-61e97',
    storageBucket: 'chorechain-61e97.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzN7WZwDh5mnVyukbiY6kgwwSfbKhko_8',
    appId: '1:581784052392:ios:9a0dd7cb8bab78007a989d',
    messagingSenderId: '581784052392',
    projectId: 'chorechain-61e97',
    storageBucket: 'chorechain-61e97.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtkZAmmpSc41zwdGDHKjks1Lww1qxQLCw',
    appId: '1:581784052392:web:a76d00e36b4bfcc27a989d',
    messagingSenderId: '581784052392',
    projectId: 'chorechain-61e97',
    authDomain: 'chorechain-61e97.firebaseapp.com',
    storageBucket: 'chorechain-61e97.firebasestorage.app',
    measurementId: 'G-J7QKNEJCMP',
  );
}
